### ISSUE TITLE
Cannot install using package managers

### ISSUE THREAD

**Issue by mpace965** [n5ro/aframe-physics-system#199]
`npm install aframe-physics-system` and `yarn add afram-physics-system` both fail

```
yarn add add-aframe-physics-system
➤ YN0000: ┌ Resolution step
➤ YN0013: │ ammo-debug-drawer@https://github.com/infinitelee/ammo-debug-drawer.git#commit=561fd698109e61456f34136a53dd08b45d4ad9ca can't b
➤ YN0013: │ three-to-ammo@https://github.com/infinitelee/three-to-ammo.git#commit=9e68a3bbe500988f2dc0096f78c12dabbdaf5548 can't be found 
info: please complete authentication in your browser...
➤ YN0001: │ Error: cannon@github:donmccurdy/cannon.js#v0.6.2-dev1: Listing the refs for https://github.com/donmccurdy/cannon.js.git failed
    at ChildProcess.<anonymous> (C:\Users\matth\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:2:412797)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.e.emit (C:\Users\matth\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:17:22627)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
➤ YN0000: └ Completed in 4s 502ms
➤ YN0000: Failed with errors in 4s 503ms
```

```
npm install aframe-physics-system
info: please complete authentication in your browser...ree buildDeps
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: three-to-cannon@1.4.1
npm WARN Found: cannon@undefined
npm WARN node_modules/cannon
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer cannon@"github:donmccurdy/cannon.js#v0.6.2-dev1" from three-to-cannon@1.4.1
npm WARN node_modules/three-to-cannon
npm WARN   three-to-cannon@"^1.3.0" from aframe-physics-system@4.0.1
npm WARN   node_modules/aframe-physics-system
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/donmccurdy/cannon.js.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matth\AppData\Local\npm-cache\_logs\2022-01-03T03_17_02_213Z-debug-0.log
```

The command that's failing is `git ls-remote`, and when running it on the repo in question, I get the following:

```
git ls-remote git@github.com:donmccurdy/cannon.js.git     
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can't seem to find this repository on GitHub either.

**Comment by zvona** [comment]
I managed to temporarily "fix" this by referring to latest (unversioned) commit. Just add in _package.json_:
`"aframe-physics-system": "git://github.com/n5ro/aframe-physics-system.git#59100ac83033cf337d26925de1f92854c2988b75"`

and it seems to install properly after that.

**Comment by entrehuihui** [comment]
npm install aframe-physics-system and yarn add afram-physics-system both fail。 can not use "aframe-physics-system": "git://github.com/n5ro/aframe-physics-system.git#59100ac83033cf337d26925de1f92854c2988b75" to install.

**Comment by Javiavan** [comment]
Same mistake as [mpac965](https://github.com/mpace965)

**Comment by arpu** [comment]
does it work if you delete the package-lock.json first?

**Comment by Javiavan** [comment]
> git://github.com/n5ro/aframe-

Hello,
Could you indicate the version of Aframe you use?
and the steps you have taken to make it work for you?
Thanks

**Comment by wayhow123** [comment]
I have the same problem, is there a solution for now?

**Comment by filran** [comment]
Hi, everyone! This worked with me: add in package.json the following code `"aframe-physics-system":"git://github.com/n5ro/aframe-physics-system"`.
